spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: ly
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  banner:
    location: banner.text

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  type-aliases-package: com.cy.store.entity
user:
  address:
    max-count: 20